swagger: '2.0'
info:
  description: API for DividendData
  version: 1.0.0
  title: DivGro Data
  # put the contact info for your development or API team
  contact:
    email: severin.gassauer@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: ec2-34-254-241-66.eu-west-1.compute.amazonaws.com
basePath: /v1
# tags are used for organizing operations
# basePath: "/v2"
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /stockdata/{ticker}:
    get:
      summary: Returns DivGro data for the ticker
      #operationId: api.stockdata.getStockData
      description: Pass ticker type and get StockData. From DB if cached or via call outbound
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: ticker
        in: path
        description: ticker symbol of stockdata to return
        required: true
        type: string
      responses:
        200:
          description: stockdata matching ticker
          schema:
            $ref: '#/definitions/StockData'
        400:
          description: bad input parameter
definitions:
    StockData:
      type: object
      required:
        - symbol
        - name
      properties:
        symbol:
          type: string
          example: ACN
        name:
          type: string
          example: Accenture Plc
        dividendhistory:
          type: array
          items:
            $ref: '#/definitions/DividendPayment'
        financials:
          $ref: '#/definitions/Financial'
    
    Financial:
      type: object
      properties:
        yield:
          type: number
          format: float
          example: 3.3.
        beta:
          type: number
          format: float
          example: 0.2
        ratios:
          type: array
          items:
            $ref: '#/definitions/Ratios'
        health:
          $ref: '#/definitions/Health'
        valuations:
          type: array
          items:
            $ref: '#/definitions/Valuation'
             
    Ratios:
      type: object
      properties:
        date:
          type: string
          format: date
        revenue:
          type: number
          format: float
        gross_margin:
          type: number
          format: float
        operating_income:
          type: number
          format: float
        operating_margin:
          type: number
          format: float
        net_income:
          type: number
          format: float
        earnings_per_share:
          type: number
          format: float
        dividends:
          type: number
          format: float
        payout_ratio:
          type: number
          format: float
        
             
    Health:
      type: object
      properties:
        current_ratio:
          type: number
          format: float
        debt_equity:
          type: number
          format: float
    
    Valuation:
      type: object
      properties:
        date: 
          type: string
          format: date
        valuation:
          type: number
          format: float
        
    DividendPayment:
      type: object
      properties:
        date: 
          type: string
          format: date
        dividend:
          type: number
          format: float
# Added by API Auto Mocking Plugin
schemes:
 - https
